### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by derhoads** [detlevn/QGIS-ConcaveHull-Plugin#9]
I'm using the "create multiple convex hulls based on a field" method and working with a large amount of data. The plugin throws an exception, and I'm sure there's some problem with my data. It would be nice if there was a more specific kind of error reporting than the broad exception that gets throw with all errors. 

Maybe printing the actual exception thrown by python instead of the generalized "Exception while computing concave hull" is an option. Alternatively, when a user is creating more than one concave hull based on a field, the successfully created hulls could be written to a memory layer. This would help to figure out where errors are coming from. 

Thanks
(by the way thanks for building this plugin!)

**Comment by detlevn** [comment]
Solved in v2.0.0
